### ISSUE TITLE
[Feature Request] Allow Mod backups

### ISSUE THREAD

**Issue by Chrisch3n** [mythridium/music#5]
Hi,

Given this statement in the documentation: 
> This mod should be safe to install and uninstall at any time, however the game is designed to automatically delete data for mods that aren't loaded. So if you uninstall this mod and load your save game, the Music data will be deleted by the game. If you re-install the mod after the data is deleted, the skill will be reset to level 1, including masteries. If you uninstall and re-install without ever loading your save game, the data should be safe and retained.

I would love, if you add a Save and Load button in the mod settings to back up the current progression in the mod.
You could copy the Import/Export function of your Combat Simulator to do so.

If the mod should break temporarily and needs to be deactivated for a time, it would be really sad to lose all the progress. 

Thanks

**Comment by mythridium** [comment]
Sorry for the delay in getting back to you on this, it's not really something that would be feasible. It would only be possible to export and import while you have already loaded your save, which doesn't help you if the mod breaks since you wouldn't be able to load successfully to perform the export, so you'd just be exporting wiped out data.

The only scenario that this would work on is having an export before you load your save, then if you had loaded your game after some issues which had gotten fixed, you could import the existing data.

The safest way, would be to create a backup of your melvor save file before loading into your save file when new patches are released to the game. The music data is encoded into your save file just like other skills, so even if the current release breaks the mod, if you had a backup of your save file before loading your save, even if you load in and wipe your music data, if you import the backup of your save and load your save after the mod has been fixed, your progress would be retained since it's in the backup.

Given that this mechanism is already readily available and it's possible to do so without needing to load your save file, it's a much better solution then if the mod itself provided this functionality. As a result will close this without action.
